version: '3.7'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./data:var/lib/mysql
    ports:
      - 3306:3306


  nginx:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root12345
      MYSQL_DATABASE: MyWordPressDatabaseName
      MYSQL_USER: MyWordPressUser
      MYSQL_PASSWORD: 12345
    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      restart: always
      ports:
        - "8000:80"
      environment:
        ["./:/var/www/html"]
    volumes:
      mysql: {}
